
## Users :: Read all users

GET {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{authToken}}

###

## Users :: Read all users (Paginated)

GET {{baseUrl}}/users?skip=1&limit=10 HTTP/1.1
Authorization: Bearer {{authToken}}

###

## Users :: Read users by user_type

GET {{baseUrl}}/users?user_type=learner HTTP/1.1
Authorization: Bearer {{authToken}}

###

## Users :: Search users by email

GET {{baseUrl}}/users?email=johndoe@sada.com HTTP/1.1
Authorization: Bearer {{authToken}}

###

## Users :: Get one user

GET {{baseUrl}}/users/gpzG5fOFKgXhCPE1PseE HTTP/1.1
Authorization: Bearer {{authToken}}


###

# Users :: Create a user
POST {{baseUrl}}/users HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "johndoe@sada.com",
  "user_type": "learner"
}

###

# Users :: Update an user (whole resource)
PUT {{baseUrl}}/users/IHABgCy6jvFegIKPCa5Y HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "userName": "Updated John Doe",
  "firstName": "Updated John",
  "lastName": "Updated Doe",
  "email": "Updated jonh.doe@sada.com",
  "groups": [
    {
      "groupName": "Updated group1",
      "type": 0
    }
  ]
}

###

# Users :: Path an user (part of resource)
PATCH {{baseUrl}}/users/4f2cc71d-ccad-41e0-8f1d-b432bdfb96de HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "enabled": false
}

###

# Users :: Delete an user
DELETE {{baseUrl}}/users/16b1c5de-901a-4e30-ab40-1a83c551d945 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

### 

# Users :: Change user status
PATCH {{baseUrl}}/users/16b1c5de-901a-4e30-ab40-1a83c551d945/status HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "disabled"
}
