import { ILearner } from '@toboggan-ws/toboggan-common';

export const learnersMock: ILearner[] = [
  {
    first_name: 'Jon',
    middle_name: 'Jon',
    last_name: 'Doe',
    suffix: '',
    prefix: '',
    preferred_name: '',
    preferred_first_name: '',
    preferred_middle_name: '',
    preferred_last_name: '',
    preferred_name_type: 'PreferredName',
    preferred_pronoun: '',
    student_identifier: '',
    student_identification_system: '',
    personal_information_verification: '',
    personal_information_type: '',
    address_type: '',
    street_number_and_name: '',
    apartment_room_or_suite_number: '',
    city: '',
    state_abbreviation: '',
    postal_code: '',
    country_name: '',
    country_code: '',
    latitude: '',
    longitude: '',
    country_ansi_code: 10000,
    address_do_not_publish_indicator: 'Yes',
    phone_number: null,
    email_address_type: 'Work',
    email_address: 'jon.doe11@gmail.com',
    email_do_not_publish_indicator: 'Yes',
    backup_email_address: 'test@mail.com',
    birth_date: '',
    gender: 'NotSelected',
    country_of_birth_code: '',
    ethnicity: '',
    organisation_email_id: 'jon.doe@foobar.com',
    employer_id: 'test_employer_id',
    affiliation: '',
    employer: '',
    employer_email: 'testid@employer.com',
    uuid: 'B1vnY2WLaUfvMoUg26AD',
    is_archived: false,
    created_time: '2022-10-17 07:09:03.475453+00:00',
    last_modified_time: '2022-10-17 07:09:03.565060+00:00',
  },
  {
    first_name: 'Arpita',
    middle_name: '',
    last_name: 'Look',
    suffix: '',
    prefix: '',
    preferred_name: 'Test',
    preferred_first_name: '',
    preferred_middle_name: '',
    preferred_last_name: '',
    preferred_name_type: 'PreferredName',
    preferred_pronoun: 'Use my name',
    student_identifier: '',
    student_identification_system: '',
    personal_information_verification: '',
    personal_information_type: '',
    address_type: '',
    street_number_and_name: '',
    apartment_room_or_suite_number: '',
    city: '',
    state_abbreviation: '',
    postal_code: '',
    country_name: '',
    country_code: '',
    latitude: '',
    longitude: '',
    country_ansi_code: 10000,
    address_do_not_publish_indicator: 'Yes',
    phone_number: null,
    email_address_type: 'Work',
    email_address: 'arpita.look@quantiphi.com',
    email_do_not_publish_indicator: 'Yes',
    backup_email_address: 'arpita.look@gmail.com',
    birth_date: null,
    gender: 'NotSelected',
    country_of_birth_code: null,
    ethnicity: null,
    organisation_email_id: 'arpita.look@quantiphi.com',
    employer_id: '',
    affiliation: '',
    employer: '',
    employer_email: 'test@mail.com',
    uuid: 'L7uyIpND0nklhbUOLCvU',
    is_archived: false,
    created_time: '2022-10-16 19:12:23.246711+00:00',
    last_modified_time: '2022-11-08 14:07:00.137412+00:00',
  },
];
